language: go
go:
    - 1.1
    - 1.1.1
    - 1.1.2
    - 1.2
    - tip
install:
    - go get github.com/ricallinson/stackr
    - go get github.com/ricallinson/httputils
    - go get github.com/ricallinson/simplebdd